### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Kendaichi** [react-auth-kit/react-auth-kit#1444]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [/ ] This is bug in the application 🐛
- [/ ] I am running the latest version
- [/ ] I checked the documentation and found no answer
- [ /] I checked to make sure that this issue has not already been filed
- [/ ] I'm reporting the issue to the correct repository

**Describe the bug** \
Error: useLocation() may be used only in the context of a <Router> component. I am using requireAuth with Router, but this occured when I add requireAuth tag in my code.

**To Reproduce** \
1. Go to 'main.js in your react app, and wrap the app.jsx with a BrowserRouter'
2. Then on your App.jsx, Created a Routes Heirarchy, with multiple route that is wrapped with routes tag.
3.Then on one of those route, add a RequireAuth tag wrapping the element.

**Expected behavior** \
Error showing this. Error: useLocation() may be used only in the context of a <Router> component.

**Screenshots**
![image](https://github.com/react-auth-kit/react-auth-kit/assets/102602290/3c70c1df-6f94-4287-9092-8cfaa947865e)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Brave
 - Version 1.58

**Failure Logs**

react-dom.development.js:18687 The above error occurred in the <RequireAuth> component:

    at RequireAuth (http://localhost:5173/node_modules/.vite/deps/react-auth-kit.js?v=d78487a3:1621:21)
    at RenderedRoute (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=d78487a3:3327:5)
    at Routes (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=d78487a3:3780:5)
    at App (http://localhost:5173/src/App.jsx?t=1695345900963:24:20)
    at Router (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=d78487a3:3727:15)
    at BrowserRouter (http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=d78487a3:4207:5)
    at AuthProvider (http://localhost:5173/node_modules/.vite/deps/react-auth-kit.js?v=d78487a3:441:21)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js:18687
react-dom.development.js:26923 Uncaught Error: useLocation() may be used only in the context of a <Router> component.
    at invariant (history.ts:494:11)
    at useLocation (hooks.tsx:104:3)
    at RequireAuth (PrivateRoute.tsx:51:22)
    at renderWithHooks (react-dom.development.js:16305:18)
    at mountIndeterminateComponent (react-dom.development.js:20074:13)
    at beginWork (react-dom.development.js:21587:16)
    at beginWork$1 (react-dom.development.js:27426:14)
    at performUnitOfWork (react-dom.development.js:26557:12)
    at workLoopSync (react-dom.development.js:26466:5)
    at renderRootSync (react-dom.development.js:26434:7)

**Additional context**
The error occurs when I added the requireAuth.

## License

[Apache-2.0](https://github.com/react-auth-kit/react-auth-kit/blob/master/LICENSE) © [React Auth Kit](https://github.com/react-auth-kit/react-auth-kit)

**Comment by ohayak** [comment]
I had this same problem. I upgraded mt react-dom-router to 6.18, I deleted node_modules folder and my yarn.lock.  Reinstall all dependencies
