### ISSUE TITLE
Maximum update depth exceeded when using RequireAuth

### ISSUE THREAD

**Issue by ohayak** [react-auth-kit/react-auth-kit#1494]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ x] This issue is related to a behaviour of the application only
- [ 2.12.7] I am running the latest version
- [ x] I checked the documentation regarding this issue and found no solution
- [ x] I checked to make sure that this issue has NOT already been filed
- [x ] I'm reporting the issue to the correct repository

**Description**\
I encounter this error:

**How to reproduce(required)** \
Detailed steps to reproduce the behaviour you experienced 

**Correct behaviour** \
Description of the correct behaviour you expected...

**Possible reason**(Optional) \
If possible give the reasoning for experiencing this unexpected behaviour

```
Uncaught Error: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
    at checkForNestedUpdates (react-dom.development.js:23583:1)
    at scheduleUpdateOnFiber (react-dom.development.js:22019:1)
    at dispatchReducerAction (react-dom.development.js:15105:1)
    at RequireAuth (PrivateRoute.js:49:1)
    at renderWithHooks (react-dom.development.js:14141:1)
    at updateFunctionComponent (react-dom.development.js:17028:1)
    at beginWork (react-dom.development.js:18740:1)
    at beginWork$1 (react-dom.development.js:23691:1)
    at performUnitOfWork (react-dom.development.js:22960:1)
    at workLoopSync (react-dom.development.js:22883:1)
checkForNestedUpdates @ react-dom.development.js:23583
scheduleUpdateOnFiber @ react-dom.development.js:22019
dispatchReducerAction @ react-dom.development.js:15105
RequireAuth @ PrivateRoute.js:49
renderWithHooks @ react-dom.development.js:14141
updateFunctionComponent @ react-dom.development.js:17028
beginWork @ react-dom.development.js:18740
beginWork$1 @ react-dom.development.js:23691
performUnitOfWork @ react-dom.development.js:22960
workLoopSync @ react-dom.development.js:22883
renderRootSync @ react-dom.development.js:22856
performSyncWorkOnRoot @ react-dom.development.js:22548
flushSyncCallbacks @ react-dom.development.js:10573
```

When using RequireAuth like this:

```javascript

const Login = () => {
  // Custom login logic
  const { setShowAuthFlow, isAuthenticated } = useDynamicContext();

  useEffect(() => {
    if (isAuthenticated) return;
    setShowAuthFlow(true);
  }, []);

  return <HomeContainer />
}


<Route path="/" element={<HomeContainer />} />
<Route path="/login" element={<Login />} />
...
<Route path={'/lobby'} element={
              <RequireAuth loginPath={'/login'}>
                <Lobby />
              </RequireAuth>
}/>
```

**Additional context**
I manged to sole the problem by rewriting RequireAuth with useEffect:

```javascript
const RequireAuth = function (_a: { children: JSX.Element; loginPath: string; }) {
    const children = _a.children
    const loginPath = _a.loginPath    
    const location = useLocation()
    const isAuthenticated = useIsAuthenticated()
    const doSignOut = useSignOut()
    React.useEffect(() => {
        if (!isAuthenticated()) {
          // Redirect them to the /login page, but save the current location they
          // were trying to go to when they were redirected. This allows us to
          // send them along to that page after they login, which is a nicer
          // user experience than dropping them off on the home page.
          doSignOut();
        }
    }, [isAuthenticated()]);

    if (!isAuthenticated()) {
        return React.createElement(Navigate, {
        to: loginPath,
        state: {
            from: location
        },
        replace: true
        });
    }

    return children;
};
```

## License

[Apache-2.0](https://github.com/react-auth-kit/react-auth-kit/blob/master/LICENSE) © [React Auth Kit](https://github.com/react-auth-kit/react-auth-kit)

**Comment by cauamillersjc** [comment]
Has anyone managed to fix this problem?

**Comment by ohayak** [comment]
> Has anyone managed to fix this problem?

juste created my Own RequireAuth and it works:

```javascript
import * as React from 'react'
import { Navigate, useLocation } from 'react-router-dom'
import { useIsAuthenticated, useSignOut } from 'react-auth-kit'

/**
 * Private Route for Components
 *
 * Solves https://github.com/react-auth-kit/react-auth-kit/issues/1494
 *
 * @remarks
 * This Component is based on {@link https://reactrouter.com/web/api/Route | reactrouter.Route}.
 * So you need to install react-route-dom before use it
 *
 * @param props
 */
const RequireAuth = function (_a: { children: JSX.Element; loginPath: string }) {
  const children = _a.children
  const loginPath = _a.loginPath
  const location = useLocation()
  const isAuthenticated = useIsAuthenticated()
  const signOut = useSignOut()

  if (!isAuthenticated()) {
    // Redirect them to the /login page, but save the current location they
    // were trying to go to when they were redirected. This allows us to
    // send them along to that page after they log in, which is a nicer
    // user experience than dropping them off on the home page.
    signOut()
    return React.createElement(Navigate, {
      to: loginPath,
      state: {
        from: location,
      },
      replace: true,
    })
  }

  return children
}

export default RequireAuth
```

**Comment by darkmatter18** [comment]
Solved in React Auth Kit v3. Please use the same.

Thanks!!
