### ISSUE TITLE
Having problem adding auth provider componennt

### ISSUE THREAD

**Issue by KyleQ1** [react-auth-kit/react-auth-kit#1503]
I added just the auth provider and it's causing my app to fail. Here's the code 
```
import "./index.css";
import { BrowserRouter, Routes, Route } from "react-router-dom";
import { AuthProvider } from "react-auth-kit";
import HomePage from "./pages/HomePage";
import ProfilePage from "./pages/ProfilePage";
import MovieReviewPage from "./pages/MovieReviewPage";
import Login from "./pages/LoginPage";

function App() {
  const user = null;

  return (
    <AuthProvider 
      authType={'cookie'}
      authName={'_auth'}
      cookieDomain={window.location.hostname}
      cookieSecure={false}
    >
      <BrowserRouter>
        <Routes>
          {!user ? (
            // redirect to login
            <Route path="" element={<Login />} />
          ) : (
            <Route path="" element={<HomePage />} />
          )}
          <Route path="profile" element={<ProfilePage />} />
          <Route path="movie" element={<MovieReviewPage />} />
        </Routes>
      </BrowserRouter>
    </AuthProvider>
  );
}

export default App;
```
Here's the error that I get:

```
ERROR
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `App`.
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `App`.
    at createFiberFromTypeAndProps (http://localhost:3000/static/js/bundle.js:36858:21)
    at createFiberFromElement (http://localhost:3000/static/js/bundle.js:36879:19)
    at reconcileSingleElement (http://localhost:3000/static/js/bundle.js:25970:27)
    at reconcileChildFibers (http://localhost:3000/static/js/bundle.js:26020:39)
    at reconcileChildren (http://localhost:3000/static/js/bundle.js:28962:32)
    at mountIndeterminateComponent (http://localhost:3000/static/js/bundle.js:29799:9)
    at beginWork (http://localhost:3000/static/js/bundle.js:31027:20)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:16037:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:16081:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:16138:35)

```
**Please provide the following information:**
 - Windows
 - Edge
 - Version 119.0.2151.72

## License

[Apache-2.0](https://github.com/react-auth-kit/react-auth-kit/blob/master/LICENSE) © [React Auth Kit](https://github.com/react-auth-kit/react-auth-kit)

**Comment by KyleQ1** [comment]
I found out the docs are for the 2.12.7 tag so the install directions should be updated to include in my opinion.
 `npm i react-auth-kit@2.12.7`

**Comment by AtharFazle** [comment]
Yeah i got that error too

**Comment by danielseow234** [comment]
Thanks so much for this, was having the same issue!

**Comment by youcefy1** [comment]
Thank u man

**Comment by darkmatter18** [comment]
Use React Auth Kit V3. Thanks!!
